# This is an example .goreleaser.yaml file with some sensible defaults.
# Replace <author> and <name> with your own values.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    # you may want to add tests and lint here as well
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags: "-s -w -X github.com/Scurra/docsync/internal/build.Version={{.Tag}} -X github.com/Scurrra/docsync/internal/build.CommitHash={{.FullCommit}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'